config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'pages#home'
  # resources :users, only: :show
  get 'search', to: 'pages#search'
  get 'dashboard', to: 'users#profile'
  resources :roofs do
    resources :bookings, only: :create
  end
  resources :bookings, only: :index
end

app/models/roof.rb
class Roof < ApplicationRecord
  CITIES = ["Tel-aviv","Herzliya","Ashdod","Ashkelon","Jerusalem","Raanana"]
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
  belongs_to :user
  has_many :bookings, dependent: :destroy
  validates :name, uniqueness: true, presence: true
  validates :price, presence: true
    mount_uploader :photo, PhotoUploader
end

app/controllers/roofs_controller.rb
class RoofsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_roof, only: [:edit, :update, :destroy]
  layout 'map', only: :index


  def index
    query = params.dig(:roofs, :query)
    if query.present?
      @roofs = Roof.where("location ILIKE ?", "%#{query}%").where.not(latitude: nil, longitude: nil)

      @markers = @roofs.map do |roof|
        {
          lng: roof.longitude,
          lat: roof.latitude,
          infoWindow: { content: render_to_string(partial: "/roofs/map_window", locals: { roof: roof }) }
        }
      end
    else
      @roofs = Roof.all
    end
  end

  def new
    @rooftop = Roof.new
  end

  def create
    @rooftop = Roof.new(rooftop_params)
    @rooftop.user = current_user
    respond_to do |format|
      if @rooftop.save
        format.html { redirect_to @rooftop, notice: 'Rooftop was successfully created.' }
        format.json { render :show, status: :created, location: @rooftop }
      else
        format.html { render :new }
        format.json { render json: @rooftop.errors, status: :unprocessable_entity }
      end
    end
  end



  def show
    @booking = Booking.new
    @rooftop = Roof.find(params[:id])
  end

  def edit
    respond_to do |format|
      if @rooftop.update(rooftop_params)
        format.html { redirect_to @rooftop, notice: 'Rooftop was successfully updated.' }
        format.json { render :show, status: :ok, location: @rooftop }
      else
        format.html { render :edit }
        format.json { render json: @rooftop.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @rooftop.update(rooftop_params)
        format.html { redirect_to @rooftop, notice: 'rooftop was successfully updated.' }
        format.json { render :show, status: :ok, location: @rooftop }
      else
        format.html { render :edit }
        format.json { render json: @rooftop.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @rooftop.destroy
      respond_to do |format|
        format.html { redirect_to rooftops_url, notice: 'Rooftop was successfully destroyed.' }
        format.json { head :no_content }
      end
  end

  def create
    @rooftop = Roof.new(rooftop_params)
    @rooftop.user = current_user
    respond_to do |format|
      if @rooftop.save
        format.html { redirect_to @rooftop, notice: 'Rooftop was successfully created.' }
        format.json { render :show, status: :created, location: @rooftop }
      else
        format.html { render :new }
        format.json { render json: @rooftop.errors, status: :unprocessable_entity }
      end
    end
  end

  def new
    @rooftop = Roof.new
  end

 private

 def rooftop_params
      params.require(:roof).permit(:name, :location, :price, :user_id,:photo,:photo_cache)
 end


  def set_rooftop
    @rooftop = Roof.find(params[:id])
  end
end

app/views/roofs/_form.html.erb
<%= simple_form_for(@rooftop) do |f| %>
  <div class="form-inputs">
    <%= f.input :name %>
     <%= f.input :location %>
      <%= f.input :price %>
       <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  </div>
  <div class="form-actions" class ="btn btn-primary">
    <%= f.button :submit %>
  </div>
<%end%>

app/views/roofs/_map_window.html.erb
<div>Hello from <%= roof.name %></div>

app/views/roofs/_roof.html.erb
<p><%= roof.name %></p>

app/views/roofs/index.html.erb
<div id="roofs">
  <h1>Rooftops</h1>
  <div>
    <div>
      <div class="row">
        <% @roofs.each do |roof| %>
          <div class="col-xs-12 col-sm-6 col-md-4">
            <%= link_to roof, class: "adjust_card_color" do %>
              <div class= "rooftop">
                <div class="roof-image" style="background-image: linear-gradient(to bottom,rgba(20,20,20, 0.8),rgba(76,76,76,0.2) 30%), url(<%= cl_image_path roof.photo, crop: :fill %>)">;

                </div>
                <div class="roof-content">
                  <div class= "roof-name"><%=roof.name%></div>
                  <div class="roof-description">
                    <p><%= roof.location %></p><h8><%= roof.price %> NIS</h8>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
      <%= link_to "Add a new Rooftop", new_roof_path, class: "btn button btn-start add" %>
    </div>
  </div>
</div>
<div
  id="map"
  data-markers="<%= @markers.to_json %>"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
  >
</div>

app/views/roofs/new.html.erb
<h1>New Rooftop</h1>
<%=render 'form', roofs: @roof%>
<%=link_to 'Back', roofs_path%>

app/views/roofs/show.html.erb
<div class="img-wrap" class="photo">
 <%= cl_image_tag @rooftop.photo %>

</div>
<div id="container-show">
  <div class="name_show">
      <h3><%=@rooftop.name%></h3>
      <p><%=@rooftop.price%> ,-ppm./<%= @rooftop.location %></p>
  </div>
  <div class="desc-show">
    <h4>Description</h4>
    <p>Huge roof top is now available in this clean and spacious building.
    there is three bar and supermarket around, and its in the central space with famous clubs around.</p><br>
    <h4>Included</h4>
    <p>Our Rooftop has everthing you could wish for. Amazing Barbecue, fast wifi and big pool. Garden and bar of course.</p><br>
    <h4>Rules</h4>
    <p>No specific rules except that from 4 am no music allowed anymore!</p><br>
  </div>

  <div class="form-show">
    <%= simple_form_for [@rooftop, @booking] do |f| %>
      <%= f.input :date, as: :string %>
      <%= f.input :period, as: :hidden %>
      <div class="container-btn">
       <span class="period on_this btn btn-default time-button" id="day">Day</span>
       <span class="period btn btn-default time-button" id="night">Night</span>
     </div>
      <div class = "submit"><%= f.submit class: "btn-start" %>
      </div>
    <% end %>
  </div>
</div>