config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'pages#home'
  # resources :users, only: :show
  get 'search', to: 'pages#search'
  get 'dashboard', to: 'users#profile'
  resources :roofs do
    resources :bookings, only: :create
  end
  resources :bookings, only: :index
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar-profile.html.erb
<div class="navbar-wagon navbar-white">
  <!-- Logo & Name of the Startup -->
  <div class="logo-div">
    <a href="/search"><img class="logo" src="https://image.ibb.co/jtnCn0/Screenshot-2018-11-20-at-10-42-42.png" alt="retro-sun-bursts-vintage-radiant-sun-rays-shape-vector-16304033" alt="logo"><h7>RoofParty</h7>
    </a>
  </div>


  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <!-- Profile picture with dropdown list -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <img src="https://image.ibb.co/m1jNkL/icon.jpg" width="30px" class="avatar dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown">
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><%= link_to 'Profile', dashboard_path %></li>
          <li><a href="#">Log Out</a></li>
        </ul>
      </div>
    </div>
  </div>
  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fas fa-bars dropdown-toggle" data-toggle="dropdown" role="button"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Sign Out</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_navbar-transparent.html.erb
<div class="navbar-wagon navbar-default navbar-fixed-top">
  <!-- Logo & Name of the Startup -->
  <a href="/search" class="navbar-wagon-brand"><img class="logo" src="https://image.ibb.co/jtnCn0/Screenshot-2018-11-20-at-10-42-42.png" alt="retro-sun-bursts-vintage-radiant-sun-rays-shape-vector-16304033" alt="logo"><h7>RoofParty</h7>
  </a>
</div>

app/views/shared/_navbar-white.html.erb
<div class="navbar-wagon navbar-white">
  <!-- Logo & Name of the Startup -->
  <div class="logo-div">
    <a href="/search"><img class="logo" src="https://image.ibb.co/jtnCn0/Screenshot-2018-11-20-at-10-42-42.png" alt="retro-sun-bursts-vintage-radiant-sun-rays-shape-vector-16304033" alt="logo"><h7>RoofParty</h7>
    </a>
  </div>

  <% if user_signed_in? %>
    <!-- Right Navigation -->
    <div class="navbar-wagon-right hidden-xs hidden-sm">
      <input type="text" placeholder="Search..">
      <!-- Profile picture with dropdown list -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <img src="https://image.ibb.co/m1jNkL/icon.jpg" width="30px" class="avatar dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown">
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li><%= link_to 'Profile', dashboard_path %></li>
            <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
          </ul>
        </div>
      </div>
    </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link"%>

  <% end %>
  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fas fa-bars dropdown-toggle" data-toggle="dropdown" role="button"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <!--<li><a href="#">Sign Out</a></li>-->
      </ul>
    </div>
  </div>
</div>